// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Island: typeof import('./node_modules/.pnpm/iles@0.7.32_sass@1.49.9/node_modules/iles/dist/client/app/components/Island.vue')['default']
    JulienCalixte: typeof import('./src/components/core/JulienCalixte.vue')['default']
    ProductionFlow: typeof import('./src/components/flow/ProductionFlow.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}

export { }
