// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/presentation/about-me.vue')['default']
    AppHeader: typeof import('./src/components/app-header.vue')['default']
    BlogPosts: typeof import('./src/components/posts/blog-posts.vue')['default']
    CrcCard: typeof import('./src/components/architecture/crc-card.vue')['default']
    CrcProject: typeof import('./src/components/architecture/crc-project.vue')['default']
    ForgettingCurve: typeof import('./src/components/smart-notes/forgetting-curve.vue')['default']
    Island: typeof import('./node_modules/.pnpm/iles@0.8.7_sass@1.56.2/node_modules/iles/dist/client/app/components/Island.vue')['default']
    JulienCalixte: typeof import('./src/components/core/julien-calixte.vue')['default']
    MyProjects: typeof import('./src/components/presentation/my-projects.vue')['default']
    OrderTag: typeof import('./src/components/core/order-tag.vue')['default']
    ProductionFlow: typeof import('./src/components/flow/ProductionFlow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToucanIcon: typeof import('./src/components/core/toucan-icon.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
